--- # Install git on target host
- hosts: workstation
  become: yes
  vars:
     target_test: git
  tasks:
  - name: install git
    yum:
      name: "{{ target_test }}"
      state: latest
 
  - name: install locate 
    yum:
      name: mlocate
      state: latest
    
  - name: Update locate database
    command: /bin/updatedb    
  
  - name: install nslookup
    yum:
      name: bind-utils
      state: latest
  
  - name: install apache  
    yum:
      name: httpd 
      state: latest
 
    notify: restart apache
  
  handlers:
      - name: restart apache
        service: 
          name: httpd
          state: restarted 
        listen: "Restart Apache services"
 
- hosts: test_server # debian
  become: yes
  vars:
     target_test: git
  tasks:
  - name: install git
    apt:
      name: "{{ target_test }}"
      state: latest

  - name: install locate
    apt:
      name: mlocate
      state: latest


