--- # Install git on target host
- hosts: workstation
  become: yes
  vars:
     target_test: git
  tasks:
    - include_tasks: Task/packages_install.yml

  handlers:
      - name: restart apache
        service:
          name: httpd
          state: restarted
        listen: "Restart Apache services"

- hosts: test_server # debian
  become: yes
  vars:
     target_test: git
  tasks:
  - name: install git
    apt:
      name: "{{ target_test }}"
      state: latest

  - name: install locate
    apt:
      name: mlocate
      state: latest
