--- # Install git on target host
- hosts: workstation # Redhat
  become: yes
  vars:
     target_test: git
  roles:
    - Test


# To update the Debian host
- hosts: test_server # debian
  become: yes
  vars:
     target_test: git
  roles:
    - Test