--- # Install git on target host
- hosts: workstation # Redhat
  become: yes
  vars:
     target_test: git
  tasks:
    - include_tasks: Task/packages_install.yml

  handlers:
    - include_tasks: Handlers/apache.yml

# To update the Debian host
- hosts: test_server # debian
  become: yes
  vars:
     target_test: git
  tasks:
    - include_tasks: Task/debian_install.yml