---
- hosts: test_appliance
  order: sorted
  
  tasks:
  - name: Install Zabbix 4 Repository
    yum:
      name: "https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm"
      state: present
  - name: Ensure Zabbix 4 packages are installed
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - mariadb
        - zabbix-agent
        - zabbix-proxy
        - zabbix-proxy-mysql
        
  - name: Start MariaDB for Zabbix Proxy
    systemd:
      name: mariadb
      state: started
      enabled: true
      
  - name: Creating Zabbix Proxy Database
    shell: "{{ item }}"
    with_list:
      - "echo 'create database `zabbixproxy`;' | mysql -u root"
      - "zcat /usr/share/doc/zabbix-proxy-mysql*4*/schema.sql.gz | mysql -u root zabbixproxy"
    args:
      executable: /bin/bash
      
  - name: Configure database users
    shell: echo "{{ item }}" | mysql --user=root
    with_items:
      - >
        UPDATE mysql.user SET Password='*pass' WHERE User='root';
        DELETE FROM mysql.user WHERE User='';
        DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
        DROP DATABASE IF EXISTS test;
        DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
        GRANT ALL PRIVILEGES ON zabbixproxy.* to 'zabbix'@'localhost';
        UPDATE mysql.user SET Password='*pass2' WHERE User='zabbix';
        FLUSH PRIVILEGES;
    args:
      executable: /bin/bash
      
  - name: Copy Zabbix Agent config
    template:
      src: /srv/ansible/files/zabbix/hv_zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
    vars:
      zabbix_main_proxy: "1.1.1.1"
      
  - name: Copy Zabbix Proxy config
    template:
      src: /srv/ansible/files/zabbix/hv_zabbix_proxy.conf.j2
      dest: /etc/zabbix/zabbix_proxy.conf
    vars:
      zabbix_main_server: "1.1.1.1"
      zbxproxy_db_pw: "pass"
      
  - name: Copy Zabbix User Parameters
    template:
      src: /srv/ansible/files/zabbix/userparams/hv_userparameter_niclink.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
    vars:
      if_prefix: "enp"
