---
- name: Remove previous backups of target VMs
  include_role:
    name: ovirt_removeVM
  loop: "{{ goodList_override }}"
  register: removed_results

- name: Run sequential backups of target VMs
  include_role:
    name: ovirt_createvmbackup
  loop: "{{ goodList_override }}"
  register: backup_results
  

- name: Send email when Job Completed
  when: "backup_results"
  mail:
   host: localhost
   port: 25
   to: "{{ ovirt_backup_admin_mail }}"
   subject: Ansible-report
   body: "Following VM Backup was completed in Ovirt: {{ goodList_override }}"
  
- name: End the Playbook
  meta: end_play
