### This playbooks combines playbooks ansible_CSV, Ovirt_Snapshot, and ovirt_ansible
### This pulls list of VMs takes snapshot of the VMs and CLones them

---
- name: Main Playbook
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    targetDOMW: 7
    selectVm: []
    sql_datadir: /ansible_ovirt
    ovirt_api_url: https://ovirt.net/ovirt-engine/api
    ovirt_username: test
    current: "{{ '%Y-%m' | strftime(ansible_date_time.epoch) }}"
    previous: "{{ '%Y-%m' | strftime (ansible_date_time.epoch | int - 2592000) }}"
    
   # TODO: See how to make the encryption work
    ovirt_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65613564633963313931333
          
    mail_body: " "

    snapshot_targets: []

    # testing overrides
    # TODO: remove for production!
    goodList_override:
      - Test1
      - Test3
      - Test4
      - VM_TestLocalRepo
      - VM_TestLocalRepo2

  roles: # Roles below are set in the order for each role to be run
    - ovirt_authenticate # authenticate with oVirt for API access
    - ovirt_getvms # get list of VMs from oVirt
    - ovirt_getbackuptargets # get list of valid targets for backup from curated lists
    - ovirt_backupvms # RUns the ovirt_createvmbackup role and displays the results 
    - ovirt_createvmbackup # Create Snapshots and clone of VMs. Backup each target VM sequentially
    - ovirt_check # Checks to make sure backups have run successfully 
    
