#Ansible Playbook for Users
---
- hosts: workstation
  become: yes
  vars: #Variables
     http_port: 80
     max_clients: 200
  tasks:
  - name: Creating a demo user #Task
    os_user:   #Module
      name: demouser
      password: secret-password
      update_password: on_create
      email: demo@example.com
      domain: "{{ demo_domain.id }}"
      state: present

  - name: Adding role to group
    os_user_role: #Module
      group: demo2
      role: demorole
      domain: "{{ demo_domain.id }}"

  - name: Ensure apache is at the latest version
    yum:
      name: httpd
      state: latest

  handlers: #Handler
    - name: restart memcached
      service:
        name: memcached
        state: restarted
    - name: Restart Apache
      service:
        name: apache
        state: restarted
